### ISSUE TITLE
Runtime exception 'Controller "c975L\ContactFormBundle\Controller\ContactFormController::display()" requires that you provide a value for the "$contactFormService" argument'

### ISSUE THREAD

**Issue by thomthom33** [975L/ContactFormBundle#4]
![capture du 2018-07-30 13-42-33](https://user-images.githubusercontent.com/39346678/43395599-ebf15604-93fe-11e8-99b3-ee912235ef23.png)
Hi, still me...
upgraded to your last release, on another workstation. Issue on injecting contactFormService on controller ?
A.Thomas

**Comment by Laurent3170** [comment]
What version of Symfony do you use? It should be auto-wired, but I’ll have a look.

**Comment by thomthom33** [comment]
i think you can close, i had deleted "c975l/email-bundle" from composer.json...

**Comment by thomthom33** [comment]
a remark : i had to add
```
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
```
to my services.yml to avoid an exception for twig filter 'localizeddate'
